services:
  mysql:
    image: mysql:8.4
    container_name: business-travel-db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: businesstravel

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: business-travel-api

    ports:
      - "5000:5000"

    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: businesstravel

    depends_on:
      - mysql

    volumes:
      - ./backend:/app
      - /app/node_modules

  backend-ai:
    build: ./backend-ai
    container_name: business-travel-ai

    ports:
      - "8000:8000"

    environment:
      DB_HOST: mysql
      DB_PORT: "3306"
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: businesstravel
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_here}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}

    depends_on:
      - mysql

    volumes:
      - ./backend-ai:/app

  frontend:
    build: ./frontend
    container_name: business-travel-web

    ports:
      - "5173:5173"

    depends_on:
      - backend
      - backend-ai

    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data:
